- type: jobRequirementOverride
  id: Mira
  jobs:
    Captain:
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 10800 #5 hours
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 10800 #5 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 10800 #5 hours
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 10800 #5 hours
    - !type:RoleTimeRequirement
      role: JobResearchDirector
      time: 10800 #5 hours
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 10800 #5 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 10800 #5 hours
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 10800 #5 hours

    HeadOfPersonnel:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours

    ChiefEngineer:
    - !type:RoleTimeRequirement
      role: JobAtmosphericTechnician
      time: 10800 #3 hours
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 10800 #3 hours
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 90000 #20 hours

    ChiefMedicalOfficer:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 10800 #3 hours
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 10800 #3 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 90000 #20 hours

    HeadOfSecurity:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 10800 #3 hours
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 36000 #10 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 #20 hours
    - !type:OverallPlaytimeRequirement
      time: 108000 #30 hours

    Quartermaster:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 10800 #3 hours
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 10800 #3 hours
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 90000 #20 hours

    ResearchDirector:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 90000 #20 hours

    Brigmedic:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 10800 #3 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 10800 #3 hours

    Detective:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 10800 #3 hours

    SecurityOfficer:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #5 hours

    Warden:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 108000 #5 hours

    SalvageSpecialist:
    - !type:DepartmentTimeRequirement
      department: Cargo
      time: 10800 #3 hours

    AtmosphericTechnician:
    - !type:RoleTimeRequirement
      role: JobStationEngineer
      time: 10800 #3 hours

    StationEngineer:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 10800 #3 hours

    TechnicalAssistant:
    - !type:OverallPlaytimeRequirement
      time: 3600 #1 hour

    Chemist:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 10800 #3 hours

    MedicalDoctor:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 3600 #1 hour

    Paramedic:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 3600 #1 hour
    - !type:OverallPlaytimeRequirement
      time: 108000 #5 hours

    Scientist:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 3600 #1 hour

    Bartender:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 0

    Borg:
    - !type:OverallPlaytimeRequirement
      time: 10800 # 3 hours

    Chef:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 0

    Lawyer:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 108000 #5 hours

    Mime:
    - !type:OverallPlaytimeRequirement
      time: 0
